export const allSurah = [
    { name: "الفاتحة", surahId: 1, english: "Al-Fatihah", fullSurahName: "Surah Al Fatihah", translation: "The Opener", place: "Makkah" },
    { name: "البقرة", surahId: 2, english: "Al-Baqarah", fullSurahName: "Surah Al Baqarah", translation: "The Cow", place: "Madinah" },
    { name: "آل عمران", surahId: 3, english: "Aal-Imran", fullSurahName: "Surah Aal Imran", translation: "Family of Imran", place: "Madinah" },
    { name: "النساء", surahId: 4, english: "An-Nisa", fullSurahName: "Surah An Nisa", translation: "The Women", place: "Madinah" },
    { name: "المائدة", surahId: 5, english: "Al-Ma'idah", fullSurahName: "Surah Al Ma'idah", translation: "The Table Spread", place: "Madinah" },
    { name: "الأنعام", surahId: 6, english: "Al-An'am", fullSurahName: "Surah Al An'am", translation: "The Cattle", place: "Makkah" },
    { name: "الأعراف", surahId: 7, english: "Al-A'raf", fullSurahName: "Surah Al A'raf", translation: "The Heights", place: "Makkah" },
    { name: "الأنفال", surahId: 8, english: "Al-Anfal", fullSurahName: "Surah Al Anfal", translation: "The Spoils of War", place: "Madinah" },
    { name: "التوبة", surahId: 9, english: "At-Tawbah", fullSurahName: "Surah At Tawbah", translation: "The Repentance", place: "Madinah" },
    { name: "يونس", surahId: 10, english: "Yunus", fullSurahName: "Surah Yunus", translation: "Jonah", place: "Makkah" },
    { name: "هود", surahId: 11, english: "Hud", fullSurahName: "Surah Hud", translation: "Hud", place: "Makkah" },
    { name: "يوسف", surahId: 12, english: "Yusuf", fullSurahName: "Surah Yusuf", translation: "Joseph", place: "Makkah" },
    { name: "الرعد", surahId: 13, english: "Ar-Ra'd", fullSurahName: "Surah Ar Ra'd", translation: "The Thunder", place: "Madinah" },
    { name: "ابراهيم", surahId: 14, english: "Ibrahim", fullSurahName: "Surah Ibrahim", translation: "Abraham", place: "Makkah" },
    { name: "الحجر", surahId: 15, english: "Al-Hijr", fullSurahName: "Surah Al Hijr", translation: "The Rocky Tract", place: "Makkah" },
    { name: "النحل", surahId: 16, english: "An-Nahl", fullSurahName: "Surah An Nahl", translation: "The Bee", place: "Makkah" },
    { name: "الإسراء", surahId: 17, english: "Al-Isra", fullSurahName: "Surah Al Isra", translation: "The Night Journey", place: "Makkah" },
    { name: "الكهف", surahId: 18, english: "Al-Kahf", fullSurahName: "Surah Al Kahf", translation: "The Cave", place: "Makkah" },
    { name: "مريم", surahId: 19, english: "Maryam", fullSurahName: "Surah Maryam", translation: "Mary", place: "Makkah" },
    { name: "طه", surahId: 20, english: "Ta-Ha", fullSurahName: "Surah Ta Ha", translation: "Ta-Ha", place: "Makkah" },
    { name: "الأنبياء", surahId: 21, english: "Al-Anbiya", fullSurahName: "Surah Al Anbiya", translation: "The Prophets", place: "Makkah" },
    { name: "الحج", surahId: 22, english: "Al-Hajj", fullSurahName: "Surah Al Hajj", translation: "The Pilgrimage", place: "Madinah" },
    { name: "المؤمنون", surahId: 23, english: "Al-Mu'minun", fullSurahName: "Surah Al Mu'minun", translation: "The Believers", place: "Makkah" },
    { name: "النور", surahId: 24, english: "An-Nur", fullSurahName: "Surah An Nur", translation: "The Light", place: "Madinah" },
    { name: "الفرقان", surahId: 25, english: "Al-Furqan", fullSurahName: "Surah Al Furqan", translation: "The Criterion", place: "Makkah" },
    { name: "الشعراء", surahId: 26, english: "Ash-Shu'ara", fullSurahName: "Surah Ash Shu'ara", translation: "The Poets", place: "Makkah" },
    { name: "النمل", surahId: 27, english: "An-Naml", fullSurahName: "Surah An Naml", translation: "The Ant", place: "Makkah" },
    { name: "القصص", surahId: 28, english: "Al-Qasas", fullSurahName: "Surah Al Qasas", translation: "The Stories", place: "Makkah" },
    { name: "العنكبوت", surahId: 29, english: "Al-Ankabut", fullSurahName: "Surah Al Ankabut", translation: "The Spider", place: "Makkah" },
    { name: "الروم", surahId: 30, english: "Ar-Rum", fullSurahName: "Surah Ar Rum", translation: "The Romans", place: "Makkah" },
    { name: "لقمان", surahId: 31, english: "Luqman", fullSurahName: "Surah Luqman", translation: "Luqman", place: "Makkah" },
    { name: "السجدة", surahId: 32, english: "As-Sajdah", fullSurahName: "Surah As Sajdah", translation: "The Prostration", place: "Makkah" },
    { name: "الأحزاب", surahId: 33, english: "Al-Ahzab", fullSurahName: "Surah Al Ahzab", translation: "The Combined Forces", place: "Madinah" },
    { name: "سبإ", surahId: 34, english: "Saba", fullSurahName: "Surah Saba", translation: "Sheba", place: "Makkah" },
    { name: "فاطر", surahId: 35, english: "Fatir", fullSurahName: "Surah Fatir", translation: "Originator", place: "Makkah" },
    { name: "يس", surahId: 36, english: "Ya-Sin", fullSurahName: "Surah Ya Sin", translation: "Ya-Sin", place: "Makkah" },
    { name: "الصافات", surahId: 37, english: "As-Saffat", fullSurahName: "Surah As Saffat", translation: "Those Ranged in Ranks", place: "Makkah" },
    { name: "ص", surahId: 38, english: "Sad", fullSurahName: "Surah Sad", translation: "Sad", place: "Makkah" },
    { name: "الزمر", surahId: 39, english: "Az-Zumar", fullSurahName: "Surah Az Zumar", translation: "The Groups", place: "Makkah" },
    { name: "غافر", surahId: 40, english: "Ghafir", fullSurahName: "Surah Ghafir", translation: "The Forgiver", place: "Makkah" },
    { name: "فصلت", surahId: 41, english: "Fussilat", fullSurahName: "Surah Fussilat", translation: "Explained in Detail", place: "Makkah" },
    { name: "الشورى", surahId: 42, english: "Ash-Shura", fullSurahName: "Surah Ash Shura", translation: "The Consultation", place: "Makkah" },
    { name: "الزخرف", surahId: 43, english: "Az-Zukhruf", fullSurahName: "Surah Az Zukhruf", translation: "The Ornaments of Gold", place: "Makkah" },
    { name: "الدخان", surahId: 44, english: "Ad-Dukhan", fullSurahName: "Surah Ad Dukhan", translation: "The Smoke", place: "Makkah" },
    { name: "الجاثية", surahId: 45, english: "Al-Jathiyah", fullSurahName: "Surah Al Jathiyah", translation: "The Crouching", place: "Makkah" },
    { name: "الأحقاف", surahId: 46, english: "Al-Ahqaf", fullSurahName: "Surah Al Ahqaf", translation: "The Wind-Curved Sandhills", place: "Makkah" },
    { name: "محمد", surahId: 47, english: "Muhammad", fullSurahName: "Surah Muhammad", translation: "Muhammad", place: "Madinah" },
    { name: "الفتح", surahId: 48, english: "Al-Fath", fullSurahName: "Surah Al Fath", translation: "The Victory", place: "Madinah" },
    { name: "الحجرات", surahId: 49, english: "Al-Hujurat", fullSurahName: "Surah Al Hujurat", translation: "The Rooms", place: "Madinah" },
    { name: "ق", surahId: 50, english: "Qaf", fullSurahName: "Surah Qaf", translation: "Qaf", place: "Makkah" },
    { name: "الذاريات", surahId: 51, english: "Adh-Dhariyat", fullSurahName: "Surah Adh Dhariyat", translation: "The Winnowing Winds", place: "Makkah" },
    { name: "الطور", surahId: 52, english: "At-Tur", fullSurahName: "Surah At Tur", translation: "The Mount", place: "Makkah" },
    { name: "النجم", surahId: 53, english: "An-Najm", fullSurahName: "Surah An Najm", translation: "The Star", place: "Makkah" },
    { name: "القمر", surahId: 54, english: "Al-Qamar", fullSurahName: "Surah Al Qamar", translation: "The Moon", place: "Makkah" },
    { name: "الرحمن", surahId: 55, english: "Ar-Rahman", fullSurahName: "Surah Ar Rahman", translation: "The Most Gracious", place: "Makkah" },
    { name: "الواقعة", surahId: 56, english: "Al-Waqi'ah", fullSurahName: "Surah Al Waqi'ah", translation: "The Inevitable", place: "Makkah" },
    { name: "الحديد", surahId: 57, english: "Al-Hadid", fullSurahName: "Surah Al Hadid", translation: "The Iron", place: "Madinah" },
    { name: "المجادلة", surahId: 58, english: "Al-Mujadila", fullSurahName: "Surah Al Mujadila", translation: "The Pleading Woman", place: "Madinah" },
    { name: "الحشر", surahId: 59, english: "Al-Hashr", fullSurahName: "Surah Al Hashr", translation: "The Exile", place: "Madinah" },
    { name: "الممتحنة", surahId: 60, english: "Al-Mumtahanah", fullSurahName: "Surah Al Mumtahanah", translation: "She That is to be Examined", place: "Madinah" },
    { name: "الصف", surahId: 61, english: "As-Saf", fullSurahName: "Surah As Saf", translation: "The Ranks", place: "Madinah" },
    { name: "الجمعة", surahId: 62, english: "Al-Jumu'ah", fullSurahName: "Surah Al Jumu'ah", translation: "Friday", place: "Madinah" },
    { name: "المنافقون", surahId: 63, english: "Al-Munafiqun", fullSurahName: "Surah Al Munafiqun", translation: "The Hypocrites", place: "Madinah" },
    { name: "التغابن", surahId: 64, english: "At-Taghabun", fullSurahName: "Surah At Taghabun", translation: "The Mutual Disillusion", place: "Madinah" },
    { name: "الطلاق", surahId: 65, english: "At-Talaq", fullSurahName: "Surah At Talaq", translation: "The Divorce", place: "Madinah" },
    { name: "التحريم", surahId: 66, english: "At-Tahrim", fullSurahName: "Surah At Tahrim", translation: "The Prohibition", place: "Madinah" },
    { name: "الملك", surahId: 67, english: "Al-Mulk", fullSurahName: "Surah Al Mulk", translation: "The Sovereignty", place: "Makkah" },
    { name: "القلم", surahId: 68, english: "Al-Qalam", fullSurahName: "Surah Al Qalam", translation: "The Pen", place: "Makkah" },
    { name: "الحاقة", surahId: 69, english: "Al-Haqqah", fullSurahName: "Surah Al Haqqah", translation: "The Reality", place: "Makkah" },
    { name: "المعارج", surahId: 70, english: "Al-Ma'arij", fullSurahName: "Surah Al Ma'arij", translation: "The Ascending Stairways", place: "Makkah" },
    { name: "نوح", surahId: 71, english: "Nuh", fullSurahName: "Surah Nuh", translation: "Noah", place: "Makkah" },
    { name: "الجن", surahId: 72, english: "Al-Jinn", fullSurahName: "Surah Al Jinn", translation: "The Jinn", place: "Makkah" },
    { name: "المزمل", surahId: 73, english: "Al-Muzzammil", fullSurahName: "Surah Al Muzzammil", translation: "The Enshrouded One", place: "Makkah" },
    { name: "المدثر", surahId: 74, english: "Al-Muddaththir", fullSurahName: "Surah Al Muddaththir", translation: "The Cloaked One", place: "Makkah" },
    { name: "القيامة", surahId: 75, english: "Al-Qiyamah", fullSurahName: "Surah Al Qiyamah", translation: "The Resurrection", place: "Makkah" },
    { name: "الانسان", surahId: 76, english: "Al-Insan", fullSurahName: "Surah Al Insan", translation: "The Man", place: "Madinah" },
    { name: "المرسلات", surahId: 77, english: "Al-Mursalat", fullSurahName: "Surah Al Mursalat", translation: "The Emissaries", place: "Makkah" },
    { name: "النبإ", surahId: 78, english: "An-Naba", fullSurahName: "Surah An Naba", translation: "The Tidings", place: "Makkah" },
    { name: "النازعات", surahId: 79, english: "An-Nazi'at", fullSurahName: "Surah An Nazi'at", translation: "Those Who Drag Forth", place: "Makkah" },
    { name: "عبس", surahId: 80, english: "Abasa", fullSurahName: "Surah Abasa", translation: "He Frowned", place: "Makkah" },
    { name: "التكوير", surahId: 81, english: "At-Takwir", fullSurahName: "Surah At Takwir", translation: "The Overthrowing", place: "Makkah" },
    { name: "الإنفطار", surahId: 82, english: "Al-Infitar", fullSurahName: "Surah Al Infitar", translation: "The Cleaving", place: "Makkah" },
    { name: "المطففين", surahId: 83, english: "Al-Mutaffifin", fullSurahName: "Surah Al Mutaffifin", translation: "The Defrauding", place: "Makkah" },
    { name: "الإنشقاق", surahId: 84, english: "Al-Inshiqaq", fullSurahName: "Surah Al Inshiqaq", translation: "The Sundering", place: "Makkah" },
    { name: "البروج", surahId: 85, english: "Al-Buruj", fullSurahName: "Surah Al Buruj", translation: "The Mansions of the Stars", place: "Makkah" },
    { name: "الطارق", surahId: 86, english: "At-Tariq", fullSurahName: "Surah At Tariq", translation: "The Morning Star", place: "Makkah" },
    { name: "الأعلى", surahId: 87, english: "Al-A'la", fullSurahName: "Surah Al A'la", translation: "The Most High", place: "Makkah" },
    { name: "الغاشية", surahId: 88, english: "Al-Ghashiyah", fullSurahName: "Surah Al Ghashiyah", translation: "The Overwhelming", place: "Makkah" },
    { name: "الفجر", surahId: 89, english: "Al-Fajr", fullSurahName: "Surah Al Fajr", translation: "The Dawn", place: "Makkah" },
    { name: "البلد", surahId: 90, english: "Al-Balad", fullSurahName: "Surah Al Balad", translation: "The City", place: "Makkah" },
    { name: "الشمس", surahId: 91, english: "Ash-Shams", fullSurahName: "Surah Ash Shams", translation: "The Sun", place: "Makkah" },
    { name: "الليل", surahId: 92, english: "Al-Layl", fullSurahName: "Surah Al Layl", translation: "The Night", place: "Makkah" },
    { name: "الضحى", surahId: 93, english: "Ad-Duha", fullSurahName: "Surah Ad Duha", translation: "The Morning Hours", place: "Makkah" },
    { name: "الشرح", surahId: 94, english: "Ash-Sharh", fullSurahName: "Surah Ash Sharh", translation: "The Relief", place: "Makkah" },
    { name: "التين", surahId: 95, english: "At-Tin", fullSurahName: "Surah At Tin", translation: "The Fig", place: "Makkah" },
    { name: "العلق", surahId: 96, english: "Al-Alaq", fullSurahName: "Surah Al Alaq", translation: "The Clot", place: "Makkah" },
    { name: "القدر", surahId: 97, english: "Al-Qadr", fullSurahName: "Surah Al Qadr", translation: "The Night of Decree", place: "Makkah" },
    { name: "البينة", surahId: 98, english: "Al-Bayyinah", fullSurahName: "Surah Al Bayyinah", translation: "The Clear Proof", place: "Madinah" },
    { name: "الزلزلة", surahId: 99, english: "Az-Zalzalah", fullSurahName: "Surah Az Zalzalah", translation: "The Earthquake", place: "Madinah" },
    { name: "العاديات", surahId: 100, english: "Al-Adiyat", fullSurahName: "Surah Al Adiyat", translation: "The Courser", place: "Makkah" },
    { name: "القارعة", surahId: 101, english: "Al-Qari'ah", fullSurahName: "Surah Al Qari'ah", translation: "The Calamity", place: "Makkah" },
    { name: "التكاثر", surahId: 102, english: "At-Takathur", fullSurahName: "Surah At Takathur", translation: "The Rivalry in World Increase", place: "Makkah" },
    { name: "العصر", surahId: 103, english: "Al-Asr", fullSurahName: "Surah Al Asr", translation: "The Declining Day", place: "Makkah" },
    { name: "الهمزة", surahId: 104, english: "Al-Humazah", fullSurahName: "Surah Al Humazah", translation: "The Traducer", place: "Makkah" },
    { name: "الفيل", surahId: 105, english: "Al-Fil", fullSurahName: "Surah Al Fil", translation: "The Elephant", place: "Makkah" },
    { name: "قريش", surahId: 106, english: "Quraysh", fullSurahName: "Surah Quraysh", translation: "Quraysh", place: "Makkah" },
    { name: "الماعون", surahId: 107, english: "Al-Ma'un", fullSurahName: "Surah Al Ma'un", translation: "The Small Kindnesses", place: "Makkah" },
    { name: "الكوثر", surahId: 108, english: "Al-Kawthar", fullSurahName: "Surah Al Kawthar", translation: "The Abundance", place: "Makkah" },
    { name: "الكافرون", surahId: 109, english: "Al-Kafirun", fullSurahName: "Surah Al Kafirun", translation: "The Disbelievers", place: "Makkah" },
    { name: "النصر", surahId: 110, english: "An-Nasr", fullSurahName: "Surah An Nasr", translation: "The Divine Support", place: "Madinah" },
    { name: "المسد", surahId: 111, english: "Al-Masad", fullSurahName: "Surah Al Masad", translation: "The Palm Fiber", place: "Makkah" },
    { name: "الإخلاص", surahId: 112, english: "Al-Ikhlas", fullSurahName: "Surah Al Ikhlas", translation: "The Sincerity", place: "Makkah" },
    { name: "الفلق", surahId: 113, english: "Al-Falaq", fullSurahName: "Surah Al Falaq", translation: "The Daybreak", place: "Makkah" },
    { name: "الناس", surahId: 114, english: "An-Nas", fullSurahName: "Surah An Nas", translation: "The Mankind", place: "Makkah" }
]